-- 创建数据库
CREATE DATABASE IF NOT EXISTS littlelink CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE littlelink;

-- 创建按钮表
CREATE TABLE IF NOT EXISTS buttons (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL COMMENT '按钮名称',
    css_class VARCHAR(100) NOT NULL COMMENT 'CSS 类名',
    icon_path VARCHAR(255) NOT NULL COMMENT '图标路径',
    icon_alt VARCHAR(100) DEFAULT '' COMMENT '图标 alt 文本',
    display_text VARCHAR(100) NOT NULL COMMENT '显示文本',
    url VARCHAR(500) DEFAULT '#' COMMENT '跳转链接',
    sort_order INT DEFAULT 0 COMMENT '排序顺序',
    is_active BOOLEAN DEFAULT TRUE COMMENT '是否启用',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_sort_order (sort_order),
    INDEX idx_is_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='按钮表';

-- 插入一些默认按钮数据（与 index.html 中的按钮对应）
INSERT INTO buttons (name, css_class, icon_path, icon_alt, display_text, url, sort_order, is_active) VALUES
('LittleLink', 'button-default', 'images/icons/littlelink.svg', 'LittleLink Logo', 'LittleLink', '#', 1, TRUE),
('Amazon', 'button-amazon', 'images/icons/amazon.svg', 'Amazon Wishlist Logo', 'Amazon Wishlist', '#', 2, TRUE),
('Amazon Music', 'button-amazon-music', 'images/icons/amazon-music.svg', 'Amazon Music Logo', 'Listen on Amazon Music', '#', 3, TRUE),
('Apple App Store', 'button-appstore', 'images/icons/apple.svg', 'Apple Logo', 'Apple App Store', '#', 4, TRUE),
('Apple Invites', 'button-invites', 'images/icons/apple-invites.svg', 'Apple Invites Logo', 'Apple Invites', '#', 5, TRUE),
('Apple Music', 'button-apple-music', 'images/icons/apple-music.svg', 'Apple Music Logo', 'Listen on Apple Music', '#', 6, TRUE),
('Apple Music Alt', 'button-apple-music-alt', 'images/icons/apple-music-alt.svg', 'Apple Music Logo', 'Listen on Apple Music', '#', 7, TRUE),
('Apple Podcasts', 'button-apple-podcasts', 'images/icons/apple-podcasts.svg', 'Apple Podcasts Logo', 'Listen on Apple Podcasts', '#', 8, TRUE),
('Apple Podcasts Alt', 'button-apple-podcasts-alt', 'images/icons/apple-podcasts-alt.svg', 'Apple Podcasts Logo', 'Listen on Apple Podcasts', '#', 9, TRUE),
('Bandcamp', 'button-bandcamp', 'images/icons/bandcamp.svg', 'Bandcamp Logo', 'Bandcamp', '#', 10, TRUE),
('Behance', 'button-behance', 'images/icons/behance.svg', 'Behance Logo', 'Behance', '#', 11, TRUE),
('Bluesky', 'button-bluesky', 'images/icons/bluesky.svg', 'Bluesky Logo', 'Bluesky', '#', 12, TRUE),
('Bluesky Alt', 'button-bluesky-alt', 'images/icons/bluesky-alt.svg', 'Bluesky Logo', 'Bluesky', '#', 13, TRUE),
('Buy Me a Coffee', 'button-coffee', 'images/icons/buy-me-a-coffee.svg', 'Buy Me A Coffee Logo', 'Buy Me A Coffee', '#', 14, TRUE),
('Cal.com', 'button-cal', 'images/icons/cal.svg', 'Cal.com Logo', 'Schedule with Cal.com', '#', 15, TRUE),
('Calendly', 'button-calendly', 'images/icons/calendly.svg', 'Calendly Logo', 'Schedule with Calendly', '#', 16, TRUE),
('Cash App', 'button-cash-app', 'images/icons/cash-app-dollar.svg', 'Cash App Logo', 'Cash App', '#', 17, TRUE),
('Dev.to', 'button-dev-to', 'images/icons/dev-to.svg', 'Dev.to Logo', 'Dev.to', '#', 18, TRUE),
('Discogs', 'button-discogs', 'images/icons/discogs.svg', 'Discogs Logo', 'Discogs', '#', 19, TRUE),
('Discogs Alt', 'button-discogs-alt', 'images/icons/discogs-alt.svg', 'Discogs Logo', 'Discogs', '#', 20, TRUE),
('Discord', 'button-discord', 'images/icons/discord.svg', 'Discord Logo', 'Discord', '#', 21, TRUE),
('Dribbble', 'button-dribbble', 'images/icons/dribbble.svg', 'Dribbble Logo', 'Dribbble', '#', 22, TRUE),
('Etsy', 'button-etsy', 'images/icons/etsy.svg', 'Etsy Logo', 'Shop on Etsy', '#', 23, TRUE),
('Facebook', 'button-faceb', 'images/icons/facebook.svg', 'Facebook Logo', 'Find us on Facebook', '#', 24, TRUE),
('Facebook Messenger', 'button-messenger', 'images/icons/messenger.svg', 'Messenger Logo', 'Chat on Messenger', '#', 25, TRUE),
('Figma', 'button-figma', 'images/icons/figma.svg', 'Figma Logo', 'Figma Community', '#', 26, TRUE),
('Fiverr', 'button-fiverr', 'images/icons/fiverr.svg', 'Fiverr Logo', 'Fiverr Gig', '#', 27, TRUE),
('Flickr', 'button-flickr', 'images/icons/flickr.svg', 'Flickr Logo', 'Flickr', '#', 28, TRUE),
('GitHub', 'button-github', 'images/icons/github.svg', 'GitHub Logo', 'GitHub', '#', 29, TRUE),
('GitLab', 'button-gitlab', 'images/icons/gitlab.svg', 'GitLab Logo', 'GitLab', '#', 30, TRUE),
('GoFundMe', 'button-gofundme', 'images/icons/gofundme.svg', 'GoFundMe Logo', 'GoFundMe', '#', 31, TRUE),
('Goodreads', 'button-goodreads', 'images/icons/goodreads.svg', 'Goodreads Logo', 'Goodreads', '#', 32, TRUE),
('Google Drive', 'button-google-black', 'images/icons/google-drive.svg', 'Google Drive Logo', 'View in Google Drive', '#', 33, TRUE),
('Google Play Store', 'button-playstore', 'images/icons/google-play.svg', 'Google Play Store Logo', 'Google Play Store', '#', 34, TRUE),
('Google Scholar', 'button-google-scholar', 'images/icons/google-scholar.svg', 'Google Scholar Logo', 'Google Scholar', '#', 35, TRUE),
('Hashnode', 'button-hashnode', 'images/icons/hashnode.svg', 'Hashnode Logo', 'Hashnode', '#', 36, TRUE),
('Instagram', 'button-instagram', 'images/icons/instagram.svg', 'Instagram Logo', 'Instagram', '#', 37, TRUE),
('Kick', 'button-kick', 'images/icons/kick.svg', 'Kick Logo', 'Kick', '#', 38, TRUE),
('Kick Alt', 'button-kick-alt', 'images/icons/kick-alt.svg', 'Kick Logo', 'Kick', '#', 39, TRUE),
('Kickstarter', 'button-kickstarter', 'images/icons/kickstarter.svg', 'Kickstarter Logo', 'Kickstarter', '#', 40, TRUE),
('Kit', 'button-kit', 'images/icons/kit.svg', 'Kit Logo', 'Kit', '#', 41, TRUE),
('Ko-fi', 'button-ko-fi', 'images/icons/ko-fi.svg', 'Ko-fi Logo', 'Support me on Ko-fi', '#', 42, TRUE),
('Last.fm', 'button-last-fm', 'images/icons/last-fm.svg', 'Last.fm Logo', 'Last.fm', '#', 43, TRUE),
('Letterboxd', 'button-letterboxd', 'images/icons/letterboxd.svg', 'Letterboxd Logo', 'Letterboxd', '#', 44, TRUE),
('Line', 'button-line', 'images/icons/line.svg', 'Line Logo', 'Line', '#', 45, TRUE),
('LinkedIn', 'button-linked', 'images/icons/linkedin.svg', 'LinkedIn Logo', 'LinkedIn', '#', 46, TRUE),
('Mailchimp', 'button-mailchimp', 'images/icons/mailchimp.svg', 'Mailchimp Logo', 'Mailchimp', '#', 47, TRUE),
('Mastodon', 'button-mastodon', 'images/icons/mastodon.svg', 'Mastodon Logo', 'Mastodon', '#', 48, TRUE),
('Matrix', 'button-matrix', 'images/icons/matrix.svg', 'Matrix Logo', 'Matrix', '#', 49, TRUE),
('Medium', 'button-medium', 'images/icons/medium.svg', 'Medium Logo', 'Medium', '#', 50, TRUE),
('Meetup', 'button-meetup', 'images/icons/meetup.svg', 'Meetup Logo', 'Meetup', '#', 51, TRUE),
('Meetup Alt', 'button-meetup-alt', 'images/icons/meetup-alt.svg', 'Meetup Logo', 'Meetup', '#', 52, TRUE),
('Microsoft', 'button-microsoft', 'images/icons/microsoft.svg', 'Microsoft Logo', 'Get it from Microsoft', '#', 53, TRUE),
('Notion', 'button-notion', 'images/icons/notion.svg', 'Notion Logo', 'Notion', '#', 54, TRUE),
('Obsidian', 'button-obsidian', 'images/icons/obsidian.svg', 'Obsidian Logo', 'Obsidian', '#', 55, TRUE),
('OnlyFans', 'button-onlyfans', 'images/icons/onlyfans.svg', 'OnlyFans Logo', 'OnlyFans (18+)', '#', 56, TRUE),
('Patreon', 'button-patreon', 'images/icons/patreon.svg', 'Patreon Logo', 'Patreon', '#', 57, TRUE),
('PayPal', 'button-paypal', 'images/icons/paypal.svg', 'PayPal Logo', 'PayPal', '#', 58, TRUE),
('Pinterest', 'button-pinterest', 'images/icons/pinterest.svg', 'Pinterest Logo', 'Pinterest', '#', 59, TRUE),
('Product Hunt', 'button-product-hunt', 'images/icons/product-hunt.svg', 'Product Hunt Logo', 'Product Hunt', '#', 60, TRUE),
('Reddit', 'button-reddit', 'images/icons/reddit.svg', 'Reddit Logo', 'Reddit', '#', 61, TRUE),
('Shop', 'button-shop', 'images/icons/shop.svg', 'Shop Logo', 'Buy with Shop', '#', 62, TRUE),
('Signal', 'button-signal', 'images/icons/signal.svg', 'Signal Logo', 'Signal', '#', 63, TRUE),
('Signal Alt', 'button-signal-alt', 'images/icons/signal-alt.svg', 'Signal Logo', 'Signal', '#', 64, TRUE),
('Slack', 'button-slack', 'images/icons/slack.svg', 'Slack Logo', 'Join Slack', '#', 65, TRUE),
('Snapchat', 'button-snapchat', 'images/icons/snapchat.svg', 'Snapchat Logo', 'Snapchat', '#', 66, TRUE),
('SoundCloud', 'button-soundcloud', 'images/icons/soundcloud.svg', 'SoundCloud Logo', 'SoundCloud', '#', 67, TRUE),
('Spotify', 'button-spotify', 'images/icons/spotify.svg', 'Spotify Logo', 'Listen on Spotify', '#', 68, TRUE),
('Spotify Alt', 'button-spotify-alt', 'images/icons/spotify-alt.svg', 'Spotify Logo', 'Listen on Spotify', '#', 69, TRUE),
('Square', 'button-square', 'images/icons/square.svg', 'Square Logo', 'Buy with Square', '#', 70, TRUE),
('Stack Overflow', 'button-stack-overflow', 'images/icons/stack-overflow.svg', 'Stack Overflow Logo', 'Stack Overflow', '#', 71, TRUE),
('Steam', 'button-steam', 'images/icons/steam.svg', 'Steam Logo', 'Steam', '#', 72, TRUE),
('Steam Alt', 'button-steam-alt', 'images/icons/steam.svg', 'Steam Logo', 'Steam', '#', 73, TRUE),
('Strava', 'button-strava', 'images/icons/strava.svg', 'Strava Logo', 'Strava', '#', 74, TRUE),
('Substack', 'button-substack', 'images/icons/substack.svg', 'Substack Logo', 'Substack', '#', 75, TRUE),
('Telegram', 'button-telegram', 'images/icons/telegram.svg', 'Telegram Logo', 'Telegram', '#', 76, TRUE),
('Threads', 'button-threads', 'images/icons/threads.svg', 'Threads Logo', 'Threads', '#', 77, TRUE),
('Threema', 'button-threema', 'images/icons/threema.svg', 'Threema Logo', 'Threema', '#', 78, TRUE),
('TikTok', 'button-tiktok', 'images/icons/tiktok.svg', 'TikTok Logo', 'TikTok', '#', 79, TRUE),
('Trello', 'button-trello', 'images/icons/trello.svg', 'Trello Logo', 'Trello', '#', 80, TRUE),
('Tumblr', 'button-tumb', 'images/icons/tumblr.svg', 'Tumblr Logo', 'Tumblr', '#', 81, TRUE),
('Twitch', 'button-twitch', 'images/icons/twitch.svg', 'Twitch Logo', 'Twitch', '#', 82, TRUE),
('Unsplash', 'button-unsplash', 'images/icons/unsplash.svg', 'Unsplash Logo', 'Unsplash', '#', 83, TRUE),
('Venmo', 'button-venmo', 'images/icons/venmo.svg', 'Venmo Logo', 'Venmo', '#', 84, TRUE),
('Vimeo', 'button-vimeo', 'images/icons/vimeo.svg', 'Vimeo Logo', 'Vimeo', '#', 85, TRUE),
('VSCO', 'button-vsco', 'images/icons/vsco.svg', 'VSCO Logo', 'VSCO', '#', 86, TRUE),
('WhatsApp', 'button-whatsapp', 'images/icons/whatsapp.svg', 'WhatsApp Logo', 'WhatsApp', '#', 87, TRUE),
('WordPress', 'button-wordpress', 'images/icons/wordpress.svg', 'WordPress Logo', 'WordPress', '#', 88, TRUE),
('X', 'button-x', 'images/icons/x.svg', 'X Logo', 'Follow on X', '#', 89, TRUE),
('YouTube', 'button-yt', 'images/icons/youtube.svg', 'YouTube Logo', 'YouTube', '#', 90, TRUE),
('YouTube Alt', 'button-yt-alt', 'images/icons/youtube-alt.svg', 'YouTube Logo', 'YouTube', '#', 91, TRUE),
('YouTube Music', 'button-yt', 'images/icons/youtube-music.svg', 'YouTube Music Logo', 'Listen on YouTube Music', '#', 92, TRUE),
('Zoom', 'button-zoom', 'images/icons/zoom.svg', 'Zoom Logo', 'Join Zoom Webinar', '#', 93, TRUE),
('Generic Blog', 'button-default', 'images/icons/generic-blog.svg', 'Blog Icon', 'Read our blog', '#', 94, TRUE),
('Generic Calendar', 'button-default', 'images/icons/generic-calendar.svg', 'Calendar Icon', 'Event RSVP', '#', 95, TRUE),
('Generic Cloud', 'button-default', 'images/icons/generic-cloud.svg', 'Cloud Icon', 'Download File', '#', 96, TRUE),
('Generic Code', 'button-default', 'images/icons/generic-code.svg', 'Code Icon', 'View the code', '#', 97, TRUE),
('Generic Computer', 'button-default', 'images/icons/generic-computer.svg', 'Computer Icon', 'Homelab Setup', '#', 98, TRUE),
('Generic Email', 'button-default', 'images/icons/generic-email.svg', 'Email Icon', 'Email Us', '#', 99, TRUE),
('Generic Email Alt', 'button-default', 'images/icons/generic-email-alt.svg', 'Email Icon', 'Email Us', '#', 100, TRUE),
('Generic Homepage', 'button-default', 'images/icons/generic-homepage.svg', 'Homepage Icon', 'Visit Homepage', '#', 101, TRUE),
('Generic Map', 'button-default', 'images/icons/generic-map.svg', 'Map Icon', 'Get Directions', '#', 102, TRUE),
('Generic Phone', 'button-default', 'images/icons/generic-phone.svg', 'Phone Icon', 'Call Us', '#', 103, TRUE),
('Generic Review', 'button-default', 'images/icons/generic-review.svg', 'Review Icon', 'Leave us a review', '#', 104, TRUE),
('Generic RSS', 'button-default', 'images/icons/generic-rss.svg', 'RSS Icon', 'RSS Subscribe', '#', 105, TRUE),
('Generic Shopping Bag', 'button-default', 'images/icons/generic-shopping-bag.svg', 'Shopping Bag Icon', 'Visit Our Shop', '#', 106, TRUE),
('Generic Shopping Tag', 'button-default', 'images/icons/generic-shopping-tag.svg', 'Shopping Tag Icon', '10% Discount', '#', 107, TRUE),
('Generic SMS', 'button-default', 'images/icons/generic-sms.svg', 'SMS Icon', 'Send us a message', '#', 108, TRUE),
('Generic Website', 'button-default', 'images/icons/generic-website.svg', 'Website Icon', 'Visit Website', '#', 109, TRUE),
('LittleLink Extended', 'button-default', 'images/icons/littlelink.svg', 'LittleLink Logo', 'LittleLink Extended', 'https://github.com/sethcottle/littlelink-extended', 110, TRUE);
